require 'pry'

array = [%w[bgcfda gecbda abdgf aedfbg eda efcbd ae agfe bdefagc fbeda],
%w[ae egdafb ea fcdeb],
%w[gfadb fbagcd cagf agecdb adg fdbcg bdcfaeg bcgfde ga efbda],
%w[cbfdge dfcebga aedcgb dgbfa],
%w[bgdeca agdbe gfb fdbgce bf eafb dfgab efbgdca gebafd dgcaf],
%w[gfbdea gfb bacedg adcgf],
%w[fbc becgdf fcbdg adcgf edafgb bgec dcgfbea gbfed bc cbeafd],
%w[gfacd gcbdf bgedfa cbdefa],
%w[ad dcafeb adcef feagc egdbaf aed cadb bgcedf cbeafgd cdfeb],
%w[dabc gabefd ecfdb ecgfbd],
%w[badcgf gdaf gadbc ebfcg fceabd gacdbe gedfbac dbf df dfcgb],
%w[df adfg cbfgad fdb],
%w[cfdb dca bdgca efgbad bafcgd fgdba cgdfea cd abdfegc bagec],
%w[agcbe adc dabcgf adc],
%w[egdab gcefd ecbgd gdebcaf eacb cb bagcdf abgfde dcegab bdc],
%w[bc gedbc dcb fgdec],
%w[gefa gedabf cfdbea bdfea bdegcfa dgbfa gfd gdcab fg fecbdg],
%w[fgd gf dbfage afbdec],
%w[fagdb be abdfe agfebdc eab aefdcb acfed bdec fceadg afegcb],
%w[be aegcfb efbcag eb],
%w[fdce fcadeg afegdb adceg cgafdb de ebcga dae cdagf abdfgce],
%w[efcd efacgd edfc afgcd],
%w[gefc defca aefbd ec gfdceba dcabge fgcad cae fcadeg bagfdc],
%w[fgcad bdfea ebadgcf ce],
%w[cdabe dcg cgef gc beadgf fegbd gcbde edgcfb gecfabd fdgcba],
%w[dcg deacb fdegab bdafgc],
%w[aefc ebcdfa eabfgd deacb ac dac gdbce gfbadce fdeba gcfbda],
%w[adc afdbe aefc ecdafb],
%w[eabfdg fdgba fac fc ebdac bfcg fcdabg bgdface bacdf fgedca],
%w[fdagcb cedba cf fc],
%w[db dbg debag fcgdeb gfeba dagfec ceadg bdfecga deagcb acbd],
%w[gbdae afebg cfedgba ecdagb],
%w[cabegd befcd aefdcb defbcag dgfb gd edg bfgecd gfdce eagfc],
%w[dbgacfe efcdg gd bdfagce],
%w[abde fbecag gcabde cefdg bgedc bgcea bgd becgdaf gdcfba bd],
%w[baegc egbdc cedgf gdfec],
%w[gedc eagbd bgadcef aebcdg dfbag eacfdb cabde fgecab ge aeg],
%w[gcbeda gabdfec dgecba gea],
%w[afedgc deabf gbfceda fg cgdea dgf bdgfec edgaf ebacgd gafc],
%w[fgd gfac cbefgad cagde],
%w[gfcbeda bfecda dgca ebgacd gbfae ecg gc gaebc cfgebd dbeca],
%w[dfcbea cegab cg cge],
%w[adefc eabdf bcafeg bd edb fcbeadg dabegc fdbg baegf fgaebd],
%w[fcead fcdea fbgd ecdbga],
%w[ac bedgc acdb gacbed bfgeadc degcfb aec cafdeg eagfb cegab],
%w[agecb gdbec abgcde agbef],
%w[cfgbead cfgdeb gafb baecd bg cgdba bgc adcfbg agfecd dcagf],
%w[dgcefb bgaf fdbcgae agcdf],
%w[agc dabc dcbgef efadgcb ebdgc baefg ac abgce ebdcag facdeg],
%w[ecbdgf ac afdgbec decfbg],
%w[fgdcb cbdeaf eabfcg cefdb gcbeadf cdeg gc afbdg cfg ecdgbf],
%w[cg eafbcd dgec cbfdge],
%w[da dbae fdaecb cdebgf afgced bedfc adf cbfeadg bdacf bfcag],
%w[dfbec egbdfc bdfca cefbd],
%w[abgfced cf cfdbe geacfd bfac bdacfe gdebc bfedga dcf bdafe],
%w[bcfa dbfce cf egdbc],
%w[dcagb feagbc dbef edafg fagebd bf fedgac fba bfagd dbcefga],
%w[fbdga dgafe cfabge fdbe],
%w[gbfce bfc acgb fbgaec bc acfedbg gface cgefad bfacde defgb],
%w[cbgfe bgfeca gacb degacf],
%w[cfgeda bac dbafg dbcfa bdfcage ecfb acedf cb ecfadb eacbgd],
%w[gafbd faced dacfb bcef],
%w[fbgec eca cbag cfegba ac efacb bgcedf caegdbf fecgad fdbea],
%w[ca acgb ebdfa agcb],
%w[acgbf cdabegf egbfd dc dacbef dacg gecabf fdc dbgfc dfcagb],
%w[dgabecf befgd acgd abgdefc],
%w[dagbfc bc agcdf cgbd bfc ebfad dfcba befgac gaecdf becdgaf],
%w[cdgb dbcg abfcdg cfb],
%w[bdcga ebdgca da cdeafg dac acfbg daeb cdbgef egbfcda bdegc],
%w[bcgad adgcbe fedacgb cegdb],
%w[gacfeb aefbg fbaegd cedgfb dfcba gc cgae abcdegf gacbf gbc],
%w[cfabd debfgac cega egca],
%w[abcfeg fdbegc ac bdafgec ebfad fcdae dcga fcged gdceaf ace],
%w[gbcfaed ebfda ac gefcab],
%w[gefbc gdeacf cag ac acgebf ceab adebcfg bfcag cgbfed bgfad],
%w[cga cagdef gac fcgba],
%w[gcbe gacfdbe dfgaeb bfecd ecdgfb dfcgae bef fcedg bcfad be],
%w[fadcb ebgc cbfda dfcab],
%w[ebcgfd dafe adcfg gfacde cfabge bcadg dfc fd fbdaceg gefac],
%w[fceadbg fcgabe fade fbeacg],
%w[fbacg cef cagebf gacefd ef bgced cfbeg dagcbf fbea cegfdab],
%w[eabf fce cdgeabf agefcb],
%w[bca gcadbfe ca edca fbgade dcageb ecbgf egacb ebadg dgcfba],
%w[cgafbd feagdb gabecd cba],
%w[fcebdg cgefb fagbce edcbg bfed eacbgfd cegda db bcd dfgcba],
%w[becdg cdbafg bedgfc cgbeafd],
%w[fcadebg edbafc cgfda decba egab gcadb gb debgfc cgbdae gdb],
%w[bgd agbe eadcbf gdb],
%w[cedfa gad ebcfda aedgc defagb gdafceb gebca dcfg dg edgacf],
%w[cdfg fadec gedac bcgae],
%w[dafegbc dcfbae dce fcebgd egdaf ecadf dfcbag acbe ec cafbd],
%w[ced dce ce ec],
%w[fegb ef bdcefg fabdgce efd fegdac cbdaf bcdef ecbdg acbedg],
%w[debgac edf ef dfacb],
%w[afgedb caedbg egfba baecf efgdb gbcadef fagd age cfegdb ag],
%w[afbec degbafc fceab eagbdc],
%w[cebd dfb dbecgaf gefcb afbegd bd fdcgb gfcebd cgdaf gfeacb],
%w[abecfg gacbfe cgfda bfceg],
%w[acdfgb ecbga ba ecgdafb deafgc aedgc aedb aecgdb bag gfecb],
%w[cgaefd gabce cdgbae ab],
%w[be fcgdae fcbag efdbcg ceb cfebg degb cdebfa fgdec gdcabfe],
%w[eb dfegc debg bce],
%w[fdecg dafgebc fgcae fgd bcfd bcged edbgfc aecdgb fbgade df],
%w[afbdecg bgfaed fcged bgedaf],
%w[cabd egdfa fbgac bcgafd ebdafgc bd eagbfc dgb fdabg cgbdef],
%w[bd bd dbg cbad],
%w[fgecba bd dgcbea gfeda gdb geacb ecbd bfadcg efcabdg bgade],
%w[dgbae befgacd ecbag afcebg],
%w[ga abefc afg fecadbg egfcbd dgfbac edgfac adbg fcgdb gbcfa],
%w[dbag fag fgdbcea dcbfeg],
%w[geacf cadfe bfaced fg fcdgae fged ebagc cfg edbfgac bfdacg],
%w[afcbged efadc fg fcg],
%w[cbd cdefbag cfadg bd bfdac abed fdabce dbegcf egabcf ecbfa],
%w[gcebdf faegcb ecdgbf fbeadcg],
%w[fagcde cgdfa daef acgde ecgadb dbcgf fca eacgbf gcafbde fa],
%w[cdage cebfga adceg deafcgb],
%w[feadgcb efcag dbfge edba dfcabg ebgfa ba gefbad ebgdcf bfa],
%w[abdefg daeb bfa fdgaecb],
%w[dgfcea becdfg bdefg abgdfec beg cgedf eb decb bgefac fgdab],
%w[beg fedgc egfacd fcedg],
%w[fcagbd adbfeg gbeda bgfde ebfcdg dfae gaceb gda ad fdbcaeg],
%w[agd gdeba fdgeab ebcga],
%w[dbcefa bfaegd fdcb fdeca agceb fcabe cfaged beagdfc fab fb],
%w[edabgf gcabe adefbc fba],
%w[eac cfgeab agdfc cdgbe gdbefc dabe gefdbca abcged ea agecd],
%w[baegdcf bfcegd gdbfce gfcebd],
%w[cdbeaf cd dcf adcgfeb defab gbfca dgbafe cead fdcab bcefdg],
%w[dfcabe fcd dc cdfgeb],
%w[gdcfbe bag dcebg dgabce cfgdba geacb bdea ba febcagd faegc],
%w[gcfea dgbfec fecag cefbgd],
%w[ebfdgc baecdfg gabfe acbg bce dgabef cdeaf gfabce ecafb cb],
%w[eabcf gdfebc egfabc gafbed],
%w[dbgacfe adgcf cedafb ecbad bdfe bf egcdab abfgec fab cbfad],
%w[bdfe fba bcfead abedc],
%w[dca afdcb befagc gacedf dbecf cgfabd da dbag ceabfdg afbgc],
%w[da adgb gfedcba dabfcg],
%w[fgcda bcgf cgfeda bfdcga gbd badfg cebafdg gcadeb bg dfbea],
%w[fcbg geacfd abfgcd bafgcde],
%w[cf gacbfe feadcb cdgaeb fbcd fcdae efdag ecf gcabedf edacb],
%w[ecabgd gbcfaed gebcad efdac],
%w[ae abcefdg faedbg agedf dgbfce gabcfe adfcg dfbge efa bdae],
%w[dcfebg fae agfdbe egfdba],
%w[fegdcab dgcaf bfd fgdab edcgaf eadgb fbcg deacbf fb gbdcfa],
%w[acefdb gdcaf fcgda gabde],
%w[ca cefa bgcfed facdbe dgbfeca adc dbacfg cabde edabg fcbde],
%w[dcbefa bedfc dfcgab dbfacg],
%w[ce bgcedf cgdef gdabfe cabefd dec aegfdcb dgcfa gcbe fgbde],
%w[cegb dce aedbfc ce],
%w[fcgaebd ef febdac feb cafbd edcfb fabecg acbdgf dfae ebgcd],
%w[feb bfe fegacb bafdec],
%w[fgdec adcb dfbega afcgeb egcbd db bcaeg beagdc dbgfcae deb],
%w[bd egcdab fecdg bed],
%w[ad dcaeg edcbag fgbdeac acd gcdfeb afegc ebda cadbfg dgbce],
%w[bfgadc dca ad cda],
%w[bdegaf egfdb afb acbegdf fgdba af feda bcfgea fbdecg abgdc],
%w[fdegb fabecg degabf adgbef],
%w[gdfbe gcf gbcda cadfbg cfdbg gceafb dfca badegc cf cedgbfa],
%w[fc fcg egcabfd bdcag],
%w[fcbag ebdcgfa ce fgaced fbgeca gfbec cgdfba fbgde efc aecb],
%w[beac ce cgbfe bfegd],
%w[dcgaef gedfb fegdabc eabfdg dgc cefgdb bafdc cg gecb gcdbf],
%w[debgcf gbcfd gbce baefgcd],
%w[bfacdeg cedgf gfdbec eca edgcfa dbeaf ca fcdea dcebga cgfa],
%w[cefgd gcedfa bdfegc aefdc],
%w[cdfea ebgdf ab adebfgc bdcegf gbda fab dagfeb ecgabf ebfad],
%w[defba cfdea ba ab],
%w[gbefcd cbedf fcaed dgfb dacgbe ebfgca fb bfecadg cfb gcbde],
%w[eabgdc egcbdf dcgbef fb],
%w[afgedb cabdefg afcdb efdgca ef abgde edf ebfad agdbec fegb],
%w[edagcfb cdfba efdagc dcebga],
%w[dcfg afbgedc efgdb agbfe fde dgbce dabegc gdbfec df fadcbe],
%w[dbfeg gdfc efd faegb],
%w[ebgdf acfge bae gbafe efdabc ba feadbg bgda gfebdc gedacfb],
%w[fbdcge dbag ab bafedc],
%w[abedcg dcagfb cf dagbc afc fceabd fbcag dfcaebg dcgf abefg],
%w[afcdbg dcfabe fcabg adgcefb],
%w[fdbc egabc bfegc fc gbfced aefbgd gfebd gfacde bgdafec fec],
%w[fbcd fedbg daefcg cef],
%w[bgacde fegad febc gfacedb gebca gaebf bfa efbgca gfadcb fb],
%w[bf dcgfeba fdcgeab fb],
%w[cgdfe fagec fbace afecdb acg fgcbead ga abfcge bcgdfa ebga],
%w[gabcef cfgde dfgcba gcbdfa],
%w[bgae ae acegfdb dbfeg dbcgfe ebgafd dfcba cgefda adebf eda],
%w[aebfdgc bedaf feabd fbadc],
%w[dfagcb cbdgea efabdcg ecdab gceaf daecbf df cdefa fad befd],
%w[afd gefca adgfcbe fd],
%w[dcfeg acgf aec degfbc ca efbcgda fcdea gfdeac faedb cegdab],
%w[egcdaf gebdcf bdaegc aefdc],
%w[cgebaf cbdagef cadgb efda degbaf fgbea dbe bgfdce edbag de],
%w[de feda dagbe agfcdbe],
%w[eagbcfd eag efcad acefgb ag gadce fadg bdgec baefcd aefgcd],
%w[bgecd edcfab baecfg ga],
%w[adbcfge eadfb faecd ab dba aebgdc ebdgf ecbfda fcba gdfaec],
%w[efcad febdg bfdgeca dba],
%w[adgfc dfegc cdfeag edf dbecagf fdabge fbgce ed dcea cagdfb],
%w[agdfbe def efd deac],
%w[cgb bfgde bdcfa fgcbd fgeadbc fcabed befcag cg dacg bgafcd],
%w[cg acfedgb bcagfe bdfagc],
%w[fcbdge egdac acgfe efgcad fc cdaf gacefbd fcg faebg dcebag],
%w[ecdag efcgda fdac dgcbea],
%w[dgabef fdabg bcdagef dcfbg fgac adfcbg fc gdbec cbf fedcba],
%w[bdcagf dfagb fabgd cf],
%w[defc cgafed ecafbg fbdag aef cdgbae gecad facdgbe ef dgaef],
%w[fe fbecga gfdba adgebc],
%w[gbdfac gcfbd dgceb bcgdfe fedabcg gdfe fbceag eg baced gec],
%w[gacfbe cdgebf cge cge],
%w[acgdbe cfa gfba cfdab cbgadf cefdb bcfadeg fa fedgac agcbd],
%w[abfg agcbd gcfeabd dfcbe],
%w[dagebf defcb dgecaf edfbac aecbdfg deacf be aceb bfdgc fbe],
%w[ebac dcfagbe feb bcae],
%w[gbcfad fadgbce ag fdcegb gbda ceagfd agc cfdbg gfcba eabcf],
%w[dagbcf gdacfb dafcgeb eabfc],
%w[dbgcea ag acg dbag aegcd bgdefca bdgce ebgfac cgbedf acefd],
%w[agecfb abdegc dgcefb agbd],
%w[dgebfca cgdfa bgafe eda cgedfa dfage fgdbac ed ecbfda egdc],
%w[befgdac daefg acfdg acdebf],
%w[fgadce dcb abgdefc cedgf fecdb cb dgcfbe bgdeca gcfb defab],
%w[fcegbd cb gdfce gfebcd],
%w[cfbdgea ec dacgf fdeab adfec dbce dbegaf cfe deafbc ebfgca],
%w[ec decb ebagfd gcfaedb],
%w[gd bcegad afdec dgbf efcdagb cdg fgdcba fgadc abfgc cgafbe],
%w[gacfb bdcgea fabcg gd],
%w[dbega afebdg ca ecabdg deca cfgbae bca gebdfac gfcbd adgcb],
%w[cab caed abc cead],
%w[cgdbfe ab fgade gefcab afcdebg agdbe dcbeg bdca abe cgabed],
%w[ba debgc gcefba cegdab],
%w[cdfegb dbafe abdgce cbfgea bfg fg cgbed dfgc bfceagd dgbfe],
%w[gf fadgcbe aebgcf cafegb],
%w[ecafb efgcab gbdecaf fbega egabd gef dfbcge fg dcbfae cafg],
%w[dcgfeb bafdceg agfbe gf],
%w[efdcbg fgbca dcgbf dbfcag faebcd abegc afc egcdabf fadg fa],
%w[fa afc adefgbc fbcedg],
%w[dfa gcdbeaf dgbafe gacfbe dcagb adcbfe febca df dbfac cefd],
%w[adgefbc daecfbg efbca bagefdc],
%w[aec fecbgd aegdc fgcad bcedaf bdcge gbea defacgb ae acbgde],
%w[ae deacg edgcb afdecb],
%w[cdab bedgf dcbegaf gdfac bc efabgc fbc cdbgf afgcbd efdagc],
%w[cfb fgebca cgfdab faedbcg],
%w[ab eacbgf bdfa fcaedg fdebagc degba bcdeg afdgeb dgeaf gab],
%w[gfdbea afdb afdb gcebd],
%w[acbed bfeacd aedgc aeg ag gdbfae egbadc bacg fcdeg gcdbfea],
%w[gdaec aefbcd gae bdaegcf],
%w[fgadbc geafb dafbgec ecdb ce bcega deacgf egc geadbc cgdab],
%w[ecgba cdbe gacedf aecgb],
%w[gbea eb cfdbaeg cebad gbdac fcdae dgebcf fcabgd adgbce ceb],
%w[dagecb ebc dagbc ebc],
%w[fbeda ga aeg aebgd agfd bdgcfae fedgab dfeacb fbaceg begcd],
%w[ga ag afcbeg bfecad],
%w[efabcg bdc fedgc adebgcf gcabed cfdbg dfba db cafgb bfcgda],
%w[dcb bdc agfbc afbegcd],
%w[fbade bcagfe cgfea cdag dfc cfade begcfd cd gecbdaf dfceag],
%w[cgda gcda fcd dc],
%w[dbcfa bg gafcde bdceafg gaecbf cbg bgde bcgad aegdc bceagd],
%w[gcdab eacgdf bg cgb],
%w[ecfagd fbadcg fgbae bdgae gbf befc facgbe gecbfad fb eagcf],
%w[gabed fb egabfcd facbegd],
%w[abef dcabf ecfdba afbcgde bgdfce af acf cagdb gaefdc bfcde],
%w[cfadb abef bcfde cgfdbe],
%w[acedbf abcfdeg bdceag bgade acdfgb aeb bgdfe eacg ea gdabc],
%w[begda dfbge ae badcg],
%w[fcda abgef da dea dacgeb fbdae cedfab bagfced ebcgfd cdfeb],
%w[bcedf edcbfg dbaceg bdcfe],
%w[dgcfba cadeb agcdb aebfgc gdaf bcfdg gac ga fgebcad fdcebg],
%w[dgacbf ebdca egfdcb bcfdg],
%w[afbedg egbd bfcdag edgcaf gbdcfae afegb fgdae gbf fcbea gb],
%w[dgbe edbg bg efdag],
%w[acb abcfde fcgead efacd eabfc dbfa ab egfcb bedgac fdcaebg],
%w[defca acb caefd acbdge],
%w[afcde dbe fbcaed aecbfgd bfec be eadbc afgdbe dacbg gcfead],
%w[be ecfb fgdabe aedgfb],
%w[fdeacg cbgfa gefb bfc bf gbafce bdefac agefc aegcdbf agcdb],
%w[bf gceaf efbg bfcaeg],
%w[fdce gacfb agbdec cgafd df caegd gdcefa bcgadef agfbde adf],
%w[fagbc fcgdea fd bfgca],
%w[gdfacb aebcg ga dgae egfcbda cedbg dbegca acg gbedfc ecbfa],
%w[ga eagd eagd edgfbc],
%w[cgbdf eb caged aegfcd egb badecg gdbce ecba egfdba dfbaecg],
%w[cagfdbe geb dgcefa dafegc],
%w[cd gbecaf acfdb cdfg cda gbdface gfbac dgacfb bfade dgecab],
%w[dfcgaeb dc bgdacef bfacd],
%w[geab fecdb gb feabcgd ebgcda gdcae gecdb gbc afegdc gbfdac],
%w[debcga bgdaec dceagb cbaged],
%w[edgfcba agd bacd afcdg degbfc acefg efdgba bgadcf da gdfbc],
%w[gcfbd dbac cgfdb gecaf],
%w[bfca fcbged dfgab cgbadf cdfabge degcab adfeg cgfbd ab bad],
%w[abcf afbc gafdb acfb],
%w[gc fdgac fgeadb afdcb gecdfa gac gecafbd cabged gfce gaefd],
%w[ecbdgfa cag bgfeda eafgcd],
%w[eagdc efdacbg cdgbe cbfdg egadfc egb aebc be gefabd dbecag],
%w[bafcgde beg gbacde dcbge],
%w[ac afbgcd gfdba fabecgd ebdafg bac cfag adgcbe abcfd cfdeb],
%w[adbegf egacdb bac acb],
%w[cafbed gf gfd cgdba eadfbcg gfdcb gbef cfdbe fdgeac gedbcf],
%w[facbegd cbdag fg fdg],
%w[fbgcd fadb fcd fd dfcbga decabg egbcf gacdb fcgeda aecfdgb],
%w[bedcafg cgdbaf fabgdec dcbgf],
%w[gb bcgeaf aebfcd cdefbga cbaef cgafb gbf dfacg gbcfed bega],
%w[bg bfacg bdfcge geba],
%w[cadfe afbgced aedfcg cebfg aeb fdageb bfcade bfaec ab bcad],
%w[bacef bcafe bfgeda baefgd],
%w[cgbde abcg cea dbegca ac agced befdgc bgafdec efgda badefc],
%w[cae eca gdfae dcega],
%w[ab fgcbed agb cafge cegba deabfcg dbgec aedgbc gfadbe bdac],
%w[ab bdca cgfedb dgceb],
%w[bfgadce cfadg fa cagdfb bcgdf fagbec gfa fbad bgcefd degca],
%w[fa ecgad gceabf dcfgb],
%w[gfd dcabegf fg cefdg cbefgd gefb ebgdc egacbd gcafdb dcfae],
%w[ebfgdc cegdabf cbafged fdg],
%w[dfecagb fbag bdcega gecdaf fg cgbad gfdacb fbcde fgd dfcgb],
%w[gfd gfd dgbeac fg],
%w[gfaed gad feacg dfaebcg deba efgbdc gefbad ad agdfbc fbdge],
%w[dga bdae fegbcd dgfabc],
%w[agdbc egdcafb caegdb afgdec cbadfg fdgba efdba bcgf gf fga],
%w[dfabg cagfdb eadbf cdfaeg],
%w[bgefac fecdabg cebdaf de aedfb ade bcefa gcafed bcde adgbf],
%w[ebcgaf fbadg ead dea],
%w[edbgc dcba egcfbad cfdage abfegd caged ebd bd gdaecb cgbef],
%w[cdebg badc edgbc ebcdg],
%w[cgfabe dce fcdba efbcg bdcef bagfecd eabgcd ed ecgbdf dgfe],
%w[fdcgbae egfd edc bfegc],
%w[fgecad gebda ebgcd egc dbecgf ce cbef cgdfb egacdfb agdbcf],
%w[edbfgc cdgbe edgfcb bcefgad],
%w[geafcd cdage ec cdegbaf gec cgafeb abgcd gebfda gafed dcef],
%w[ce gdbfea egdabfc gec],
%w[be abdgfc daecgfb bae dbfag gfdeba dbafe gbfeac egdb dfcae],
%w[bdge eba ecfgba gcaedbf],
%w[bcge gbeadcf acg bfcdga bfcaeg cfaeg gc feabc bfaecd gedfa],
%w[bfeac begc fgdbca bgfedac],
%w[gfbed ce ced fceabd dabegf bcdgef egcf becfagd gcdbe gcadb],
%w[ce ec bdfaceg cdeafgb],
%w[gfdea db cfdgbe badc gbaec ebfagc bde dgbcae egbda cbgedfa],
%w[badegc cbeagdf bd egfbcad],
%w[deabcg egbca agfdbc edagfb abe eb afbdceg efcag becd agcdb],
%w[bced eb be bea],
%w[ebfgda bgade dbcea geaf gcbadf dgfba eg gcedabf geb cgfbed],
%w[edabg ebg cedgfb bgdcfa],
%w[fc adgbecf fbcd abgfdc cgfab aedcfg dgcab gfeab cfg cbdgae],
%w[fcg badegcf bgdac fgc],
%w[edg egbda dafbgec begc aedcb cadgeb eg eacdfg gafbd cebadf],
%w[dfgba bdegac cbge afdbec],
%w[bgfecad gdbaf afdbeg egafcb db dba fdbace egafb gdeb dcgfa],
%w[fcbade fdagbe bad cdbefa],
%w[bcgedf ecba bagcef beg cgafed eb gfedcab gfbad efgba egafc],
%w[bace fbgdec cbgefa beg],
%w[dgfecb fcd edfbag bcfade fc caegd bcgedfa defab caefd cbaf],
%w[dbeafcg fc fabed dcf],
%w[ceafg fbad cfeba edbca afebdc bf cegbad bcdfge cgdefab feb],
%w[gdbecf faebdgc dcaeb ebf],
%w[cgdfba cdabf gfedca efgcadb baegfd bcfg fc caebd gdafb caf],
%w[cgfb dgcfab befgadc debgcfa],
%w[ebfgca abcfe gca bagde bgcae dbgcfa efbadc gcef agefbcd cg],
%w[abegc cbfae acefbgd cag],
%w[dfegac gedc bcdaef abgfd egf ge fagecb agefd fecdbga ecfda],
%w[gbafd dacbef gdefac gef],
%w[feb begcdf fcab edcafb bf aefdc gbade bfead daegfc feagcbd],
%w[bcfeagd gcdbfe fbceda fb],
%w[baefgcd fedcb cfbaed dgc abdgf bdfgc bcedgf gc gcfe aegdbc],
%w[ceafgbd fbcdge bgdface efbdgc],
%w[fd gbdae bfda ebfgdc edf gfdea caegf aedgcfb fadgbe bcagde],
%w[abedg adegb efd fcaedgb],
%w[befg gecdb dbcgafe adebcf dge ecfbd bcefdg aecgdf ge bgcda],
%w[bgfe gdebc dge ge],
%w[cfdgb be aecfg gefdbc bgfec afbdgec cdabfe egbd cgabdf cbe],
%w[fbdgc eagcf eb faegc],
%w[gfdbae aedcfg gbcfed bcde dbefgac gfacb ceg bdgfe ce efcbg],
%w[efcbg ce edcb ebgadf],
%w[ba fecba dbcgfae gcab gfcade febdc adfegb fab aegfbc gcfae],
%w[adfgbce gebdaf cefba fba],
%w[eadbf acfde cfdeab bagfcde bgfcae eab gafdce cedb dbgfa eb],
%w[bea fgeacd eb fegabc],
%w[ecb baedc ec adbfgc cedf faedcb acdfb fdgaebc agbde aegcbf],
%w[fdce cbfdage bdacgf cedf],
%w[fegc cefgdb fdbge bfg badgcf eabcdf fg begad dafgceb fedcb],
%w[bgf fdbec gf ebdacf],
%w[gfecdab gbeac aebd be eacgd ebc dfegca cbagf agbdce bcdgfe],
%w[bec ecdga ecb gabec],
%w[cb bcfg cgdfa adegfc bca aegdb afcebd gcdfab dbgca becfdag],
%w[bc badcgf bca fcbg],
%w[gabdce dc fbgdc gbfec cfda fgadcb bafgd fbdeag abdcegf cdg],
%w[fcda adbfg cfgbead dgacfbe],
%w[ecgab gbdecaf bcfa cdegbf eabgdf fgeabc ba egfcb gedca gba],
%w[fcbeg gacbfe ecdbafg deacg],
%w[agc bgfca cg cgafdbe dcfg dcfagb fbdag cabef gdbace gdefab],
%w[dcfg agbfc bcfea cag],
%w[cagb ga dfcga fdaebc fdebga cbdafg gfcbdea fcgde cfbad afg],
%w[cbga cedgf cdbfa afdbcge],
%w[cafgdeb aebfd gfbeda ebcgdf agcbf egf decbaf egda abgfe ge],
%w[bgacf bdfea agfbe beadcf],
%w[be agbefdc aedfgc gabfc adgfeb egb efdag afgbe deba bgfedc],
%w[fedgacb dcafge bdae ebad],
%w[cfbae dcaegf cdbfaeg fcebga efgca cdfab ageb gcbfde ebc be],
%w[acfgde be be bcfagde],
%w[bafdgce cea gdbcfe ae agecd agcdbe ebfcad agbe bcdeg fgadc],
%w[cebgad ecbgd cbdeg gaeb],
%w[bgce agefcbd egbcfa eg fadgb bfcae dfbcae egfab gae fdcega],
%w[age gafcbe eacfbg gea],
%w[fgacde gfaedb ebacf gc gdfc dcbeafg fadge gec bdcgea cgfea],
%w[fdagcbe gfdc aefgcbd gc],
%w[gb acfdgb bga aedgf bafdg abdfecg gacfeb bgdc bfcad fcedba],
%w[fgaecbd dabcf bcdg bg]]

# array = [%w[be cfbegad cbdgef fgaecd cgeb fdcge agebfd fecdb fabcd edb],
# %w[fdgacbe cefdb cefbgd gcbe],
# %w[edbfga begcd cbg gc gcadebf fbgde acbgfd abcde gfcbed gfec],
# %w[fcgedb cgb dgebacf gc],
# %w[fgaebd cg bdaec gdafb agbcfd gdcbef bgcad gfac gcb cdgabef],
# %w[cg cg fdcagb cbg],
# %w[fbegcd cbd adcefb dageb afcb bc aefdc ecdab fgdeca fcdbega],
# %w[efabcd cedba gadfec cb],
# %w[aecbfdg fbg gf bafeg dbefa fcge gcbea fcaegb dgceab fcbdga],
# %w[gecf egdcabf bgf bfgea],
# %w[fgeab ca afcebg bdacfeg cfaedg gcfdb baec bfadeg bafgc acf],
# %w[gebdcfa ecba ca fadegcb],
# %w[dbcfg fgd bdegcaf fgec aegbdf ecdfab fbedc dacgb gdcebf gf],
# %w[cefg dcbef fcge gbcadfe],
# %w[bdfegc cbegaf gecbf dfcage bdacg ed bedf ced adcbefg gebcd],
# %w[ed bcgafe cdgba cbgef],
# %w[egadfb cdbfeg cegd fecab cgb gbdefca cg fgcdab egfdb bfceg],
# %w[gbdfcae bgc cg cgb],
# %w[gcafb gcf dcaebfg ecagb gf abcdeg gaef cafbge fdbac fegbdc],
# %w[fgae cfgab fg bagce]]

sets = []
array.map! { |arr| arr.length < 5 ? arr : arr.sort_by(&:length) }
array.each_slice(2) { |set| sets << set }
numbers = []
sets.each do |set|
  set[1].map! do |digit|
    case digit.length
    when 7
      8
    when 2
      1
    when 3
      7
    when 4
      4
    when 5
      if digit.count(set[0][0]) == 2
        3
      elsif digit.count(set[0][2]) == 3
        5
      else
        2
      end
    when 6
      if digit.count(set[0][2]) == 4
        9
      elsif digit.count(set[0][0]) == 2
        0
      else
        6
      end
    end
  end
  numbers << set[1].join.to_i
end
p numbers.sum
